src/objects/Activite__c.object
<CustomObject>
    <fields>
        <fullName>cout__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>date__c</fullName>
        <label>date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>delai__c</fullName>
        <label>Deadline</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>plan_Action__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Action Plan</label>
        <referenceTo>Plan_Action__c</referenceTo>
        <relationshipLabel>Actions Plan Activites</relationshipLabel>
        <relationshipName>Actions_Plan_Activites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>responsable__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Actions Plan Activites</relationshipLabel>
        <relationshipName>Actions_Plan_Activites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>statut__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Fait</fullName>
                </value>
                <value>
                    <fullName>Non fait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Corrective</fullName>
                </value>
                <value>
                    <fullName>Preventive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Action Plan Activity</label>
    <nameField>
        <label>activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions Plan Activites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan_Action__c.object
<CustomObject>
    <fields>
        <fullName>risque_Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>detected risk</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>PA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>responsable__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActiviteController.cls
public with sharing class ActiviteController {
	
	@AuraEnabled
	public static Activite__c getElementById(String Id){
		return [SELECT Id,cout__c,date__c,delai__c,Name,plan_Action__c,plan_Action__r.Name,responsable__c,responsable__r.Name,statut__c,type__c,plan_Action__r.risque_Entite__r.Entite__c,plan_Action__r.ParamRisqueEntite__r.entite__c FROM Activite__c where Id=:Id ];	
	}
	
    @AuraEnabled
	public static List<Activite__c> findAllByPlanAction(String planAction){
		return [SELECT Id,cout__c,date__c,delai__c,Name,plan_Action__c,plan_Action__r.Name,responsable__c,responsable__r.Name,statut__c,type__c FROM Activite__c where plan_Action__c=:planAction order by date__c desc];
	}
	
	@AuraEnabled
	public static List<Activite__c> findAll(){
		return [SELECT Id,cout__c,date__c,delai__c,Name,plan_Action__c,plan_Action__r.Name,responsable__c,responsable__r.Name,statut__c,type__c FROM Activite__c order by date__c desc];
	}
	
	@AuraEnabled
	public static Activite__c add(Activite__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Activite__c remove(Activite__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<Contact> findUserEntites(String entite){
		return [select Id,Name,AccountId from Contact where AccountId=:entite];
	}
	
	
}