src/objects/Activite__c.object
<CustomObject>
    <label>Action Plan Activity</label>
    <nameField>
        <label>activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions Plan Activites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicateur_Activite__c.object
<CustomObject>
    <fields>
        <fullName>activite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>activity</label>
        <referenceTo>Activite__c</referenceTo>
        <relationshipLabel>Activities  Indicators</relationshipLabel>
        <relationshipName>Activities_Indicators</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Activity indicator</label>
    <nameField>
        <label>Activity indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities  Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IndicateurActiviteController.cls
public with sharing class IndicateurActiviteController {
  @AuraEnabled
	public static List<Indicateur_Activite__c> findAll(String activite){
		return [SELECT Id,activite__c,activite__r.Name,description__c,Name FROM Indicateur_Activite__c where activite__c=:activite order by Name];
	}
	
	@AuraEnabled
	public static Indicateur_Activite__c add(Indicateur_Activite__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Indicateur_Activite__c remove(Indicateur_Activite__c item){
		delete item;
		return item;
	}  
	@AuraEnabled
	public static Indicateur_Activite__c getElementById(String Id){
		return [SELECT Id,activite__c,activite__r.Name,Name,description__c FROM Indicateur_Activite__c where Id=:Id];
	}
}