src/objects/Activite__c.object
<CustomObject>
    <fields>
        <fullName>plan_Action__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Action Plan</label>
        <referenceTo>Plan_Action__c</referenceTo>
        <relationshipLabel>Actions Plan Activites</relationshipLabel>
        <relationshipName>Actions_Plan_Activites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Action Plan Activity</label>
    <nameField>
        <label>activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions Plan Activites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Categorie_Risque__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk category</label>
    <nameField>
        <label>Category Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Indicateur_Activite__c.object
<CustomObject>
    <fields>
        <fullName>activite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>activity</label>
        <referenceTo>Activite__c</referenceTo>
        <relationshipLabel>Activities  Indicators</relationshipLabel>
        <relationshipName>Activities_Indicators</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Activity indicator</label>
    <nameField>
        <label>Activity indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities  Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan_Action__c.object
<CustomObject>
    <fields>
        <fullName>risque_Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>detected risk</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>PA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IndicateurActiviteController_Test.cls
/**
 * @author: Laye
 * @date: Creation: 29/05/2018
 * @description: class de test d'ImpactRisqueController
 */
@isTest
public class IndicateurActiviteController_Test {
	@testSetup
    static void setUp(){
        List<Account> entites = Orm_TestFactory.generateStructure();
        List<Categorie_Risque__c> categories = Orm_TestFactory.generateCategorieRisque();
		List<Risque__c> risques = Orm_TestFactory.generateRisque(categories);
		List<Contact> riskManagers = Orm_TestFactory.generateRiskManager(entites[0].Id);
		List<Risque_Entite__c> risqueDetectes = Orm_TestFactory.generateRisqueDetecte(risques[0].Id, riskManagers[0].Id, entites[0].Id);
		List<Plan_Action__c> actionsPlan = Orm_TestFactory.generatePlanActions(risqueDetectes, riskManagers[0].Id);
		List<Activite__c> activites = Orm_TestFactory.generateActivites(actionsPlan[0]);
        Orm_TestFactory.genererIndicateurActivites(activites[0]);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @date: Modification: 05/06/2018
     * @description: methode de test de findAll
     */
    @isTest
    static void findAll_Test(){
        String methodName='findAll';
        System.debug('### start- '+methodName);
        Indicateur_Activite__c indicateurActivite = [SELECT Id, activite__c FROM Indicateur_Activite__c limit 1];
		System.assertEquals(IndicateurActiviteController.findAll(indicateurActivite.activite__c).size(), 20);        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @date: Modification: 05/06/2018
     * @description: methode de test d'add
     */
    @isTest
    static void add_Test(){
        String methodName='add';
        System.debug('### start- '+methodName);
        Id activiteId = [SELECT ID FROM Activite__c limit 1].Id;
		Indicateur_Activite__c indicateurActivite = new Indicateur_Activite__c(Name= 'Name', description__c= 'description', activite__c= activiteId);
        IndicateurActiviteController.add(indicateurActivite);
        System.assertNotEquals(indicateurActivite.Id, null);
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @date: Modification: 05/06/2018
     * @description: methode de test de remove
     */
    @isTest
    static void remove_Test(){
        String methodName='remove';
        System.debug('### start- '+methodName);
		Indicateur_Activite__c indicateurActivite = [SELECT Id, activite__c FROM Indicateur_Activite__c limit 1];
        integer size = IndicateurActiviteController.findAll(indicateurActivite.activite__c).size();
        IndicateurActiviteController.remove(indicateurActivite);
        System.assertEquals(IndicateurActiviteController.findAll(indicateurActivite.activite__c).size(), size - 1);
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 05/06/2018
     * @description: methode de test getElementById
     */
    @isTest
    static void getElementById_Test(){
        String methodName='getElementById';
        System.debug('### start- '+methodName);
        Id indicateurActiviteId = [SELECT Id FROM Indicateur_Activite__c limit 1].Id;
        Indicateur_Activite__c indicateurActivite = IndicateurActiviteController.getElementById(indicateurActiviteId);
        System.assertNotEquals(indicateurActivite.Id, null);
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 05/06/2018
     * @description: methode de test de getObjectFields
     */
    @isTest
    static void getObjectFields_Test(){
        String methodName='getObjectFields';
        System.debug('### start- '+methodName);
        Map<String,String> fields = IndicateurActiviteController.getObjectFields();
        System.assertNotEquals(fields.size(), null);
        System.debug('### end- '+methodName);
    }
}