src/objects/Activite__c.object
<CustomObject>
    <label>Action Plan Activity</label>
    <nameField>
        <label>activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions Plan Activites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mesure__c.object
<CustomObject>
    <fields>
        <fullName>activite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>activity</label>
        <referenceTo>Activite__c</referenceTo>
        <relationshipName>Measure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Activity measurement</label>
    <nameField>
        <label>Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MesureController.cls
public with sharing class MesureController {
    @AuraEnabled
	public static List<Mesure__c> findAll(String activite){
		return [SELECT Id,activite__c,activite__r.Name,description__c,Name FROM Mesure__c where activite__c=:activite order by Name];
	}
	
	@AuraEnabled
	public static Mesure__c add(Mesure__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Mesure__c remove(Mesure__c item){
		delete item;
		return item;
	}
	@AuraEnabled
	public static Mesure__c getElementById(String Id){
		return [SELECT Id,activite__r.Name,activite__c,description__c,Name FROM Mesure__c where Id=:Id];
	}
}