src/objects/Categorie_Mesure_Prevention__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Prevention Measure Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prevention Measure Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mesure_Prevention__c.object
<CustomObject>
    <fields>
        <fullName>CategorieMesurePrevention__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Measurement Prevension</label>
        <referenceTo>Categorie_Mesure_Prevention__c</referenceTo>
        <relationshipName>Measures_Prevention</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipName>Measures_Prevention</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>preventative measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>preventative measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MesurePreventionController.cls
public with sharing class MesurePreventionController {
     @AuraEnabled
	public static List<Mesure_Prevention__c> findAll(String risque){
		return [SELECT Id,Name,Description__c,CategorieMesurePrevention__r.Name,Risque__c FROM Mesure_Prevention__c where Risque__c=:risque order by Name];
	}
	
	 @AuraEnabled
	public static List<Mesure_Prevention__c> filterFromCategorie(String categorie, String risque){
		return [SELECT Id,Name,Description__c,CategorieMesurePrevention__r.Name,Risque__c FROM Mesure_Prevention__c where Risque__c=:risque and CategorieMesurePrevention__c=:categorie order by Name];
	}
	
	@AuraEnabled
	public static Mesure_Prevention__c add(Mesure_Prevention__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Mesure_Prevention__c remove(Mesure_Prevention__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<Categorie_Mesure_Prevention__c> getCategorieMesurePreventions(){
		return [SELECT Id,Name FROM Categorie_Mesure_Prevention__c order by Name];
	}
	@AuraEnabled
	public static Mesure_Prevention__c getElementById(String Id){
		return [SELECT Id,Name,Description__c,CategorieMesurePrevention__r.Name,Risque__c FROM Mesure_Prevention__c where Id=:Id];
	}
}