src/objects/Categorie_Risque__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk category</label>
    <nameField>
        <label>Category Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Impact__c.object
<CustomObject>
    <label>Risk Impact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Impacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Impact_Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>ImpactRisque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Impact</label>
        <referenceTo>Impact__c</referenceTo>
        <relationshipName>Entity_Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>risque_Entite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk entity</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipName>Entity_Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk Impact</label>
    <nameField>
        <displayFormat>Impact-{0000}</displayFormat>
        <label>Impact  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detected Risk Impacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ParamRisqueEntite__c.object
<CustomObject>
    <fields>
        <fullName>entite__c</fullName>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Entite_Risk_Parameters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>risque__c</fullName>
        <label>risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipName>Entite_Risk_Parameters</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>seuilApparution__c</fullName>
        <label>Apparition threshold</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Risk Tracking Parameter</label>
    <nameField>
        <label>Entite Risk Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Tracking Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Action__c.object
<CustomObject>
    <fields>
        <fullName>commentaire__c</fullName>
        <label>comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>etat__c</fullName>
        <defaultValue>true</defaultValue>
        <label>state</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>risque_Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>detected risk</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>PA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <fields>
        <fullName>categorieRisque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Category</label>
        <referenceTo>Categorie_Risque__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Date_Detection__c</fullName>
        <label>Date of detection</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>criticite__c</fullName>
        <formula>( frequence__c  +  gravite__c ) *  maitrise__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Criticality</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>etat__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>frequence__c</fullName>
        <label>Frequency</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gravite__c</fullName>
        <label>Gravity</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>maitrise__c</fullName>
        <label>Mastery</label>
        <precision>17</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>responsable__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RisqueEntiteController.cls
public with sharing class RisqueEntiteController {
    @AuraEnabled
	public static List<Risque_Entite__c> findAllByEntite(String entite){
		return [SELECT Id,Date_Detection__c,Entite__r.Name,description__c,frequence__c,gravite__c,maitrise__c,criticite__c,
		               responsable__r.Name,Risque__r.Name,Entite__c,etat__c,(SELECT Id,ImpactRisque__r.Name, ImpactRisque__r.description__c,risque_Entite__r.Risque__r.Name 
		                                                                     FROM Entity_Risk_Impacts__r),
		                                                                    (SELECT Id,commentaire__c,Name 
		                                                                     FROM Action_Plans__r) 
		        FROM Risque_Entite__c 
		        WHERE Entite__c=:entite 
		        order by responsable__r.Name ];
	}
	
	@AuraEnabled
	public static List<Risque_Entite__c> findAll(){
		return [SELECT Id,Date_Detection__c,Entite__r.Name,description__c,frequence__c,gravite__c,maitrise__c,criticite__c,responsable__r.Name,Risque__r.Name,Entite__c,etat__c FROM Risque_Entite__c order by responsable__r.Name ];
	}
	
	
	 @AuraEnabled
	public static List<Risque_Entite__c> filterFromCategorieEntite(String categorie, String entite){
		return [SELECT Id,Date_Detection__c,Entite__r.Name,description__c,frequence__c,gravite__c,maitrise__c,criticite__c,responsable__r.Name,Risque__r.Name,Entite__c,Risque__r.categorieRisque__c FROM Risque_Entite__c where Entite__c=:entite and Risque__r.categorieRisque__c=:categorie order by responsable__r.Name ];
	}
	
	 @AuraEnabled
	public static List<Risque_Entite__c> filterFromCategorie(String categorie){
		return [SELECT Id,Date_Detection__c,Entite__r.Name,description__c,frequence__c,gravite__c,maitrise__c,criticite__c,responsable__r.Name,Risque__r.Name,Entite__c,Risque__r.categorieRisque__c FROM Risque_Entite__c where Risque__r.categorieRisque__c=:categorie order by responsable__r.Name ];
	}
	
	@AuraEnabled
	public static Risque_Entite__c add(Risque_Entite__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Risque_Entite__c getElementById(String Id){
		return [SELECT Id,Date_Detection__c,description__c,frequence__c,gravite__c,maitrise__c,criticite__c,
		Entite__r.Name,Entite__r.Phone,Entite__r.Website,Entite__r.Type,Entite__r.Description,Entite__c,etat__c,
		responsable__r.Name,Risque__r.Name,Risque__c FROM Risque_Entite__c where Id=:Id];
	}
	
	@AuraEnabled
	public static Risque_Entite__c remove(Risque_Entite__c item){
		delete item;
		return item;
	}
	
	@AuraEnabled
	public static List<Contact> findUserEntites(String entite){
		return [select Id,Name from Contact where AccountId=:entite];
	}
	
	@AuraEnabled
	public static List<Categorie_Risque__c> getCategorieRisques(){
		return [SELECT Id,Name FROM Categorie_Risque__c order by Name];
	}
	
	@AuraEnabled
	public static List<Risque__c> findRisques(){
		return [SELECT Id,Name FROM Risque__c order by Name]; 
	}
	
	@AuraEnabled
	public static ParamRisqueEntite__c getParamRisqueEntite(String Id){
		return [SELECT Id,risque__c,seuilApparution__c FROM ParamRisqueEntite__c where Id=:Id];
		
	}

	@AuraEnabled
	public static List<Risque_Entite__c> findAllByManagerRisk(String idRiskManager){
		return [SELECT Id,Date_Detection__c,Entite__r.Name,description__c,frequence__c,gravite__c,
		               maitrise__c,criticite__c,responsable__c,responsable__r.Name,Risque__r.Name,Entite__c,etat__c 
		               FROM Risque_Entite__c
		               where responsable__c=:idRiskManager
		               order by responsable__r.Name ];
	}
	
	@AuraEnabled
    public static Map<String,String> getObjectFields(){
        //variable for storing object field api name and field label
        Map<String,String> objectFields=new Map<String,String>();
        //field type
        String type='Risque_Entite__c';
        //get field description
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType leadSchema = schemaMap.get(type);
        Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();
        objectFields.put('label', SObjectType.Risque_Entite__c.getLabel());
        objectFields.put('labelPlural', SObjectType.Risque_Entite__c.getLabelPlural());
        //loop over description
        for (String fieldName: fieldMap.keySet()) {
           //fill variable
            objectFields.put(fieldName, fieldMap.get(fieldName).getDescribe().getLabel());
        }
        //get field description
       	type='Account';
         leadSchema = schemaMap.get(type);
         fieldMap = leadSchema.getDescribe().fields.getMap();
        //loop over description
        for (String fieldName: fieldMap.keySet()) {
           //fill variable
            objectFields.put(fieldName, fieldMap.get(fieldName).getDescribe().getLabel());
        }
        //return map with fields api name as key and field label as value
        System.debug('###-result'+objectFields);
        return objectFields;
    }
   
}