src/objects/Categorie_Risque__c.object
<CustomObject>
    <label>Risk category</label>
    <nameField>
        <label>Category Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Processus__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessusRisque__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Risk_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>risqueEntite__c</fullName>
        <label>Risk Entity</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipName>Risk_Process</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process risk</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Risk Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessusRisqueController_Test.cls
/**
 * @author: David
 * @date: Creation: 05/06/2018
 * @description: class de test de ProcessusRisqueController
 */
@isTest
public class ProcessusRisqueController_Test {
	@testSetup
    static void setUp(){   
    	List<Account> structures = Orm_TestFactory.generateStructure();
        List<Categorie_Risque__c> categories = Orm_TestFactory.generateCategorieRisque();
    	List<Contact>  responsables = Orm_TestFactory.generateRiskManager(structures[0].Id);    	
    	List<Risque__c> risques = Orm_TestFactory.generateRisque(categories);
    	List<Risque_Entite__c> risqueEntite=Orm_TestFactory.generateRisqueDetecte(risques[0].Id, responsables[0].Id,  structures[0].Id);
    	List<Processus__c> processus = Orm_TestFactory.generateProcessus(responsables[0].Id, responsables[0].Id,  structures[0].Id);  
    	Orm_TestFactory.generateProcessusRisque(processus[0].id,risqueEntite[0].id);
    	     
    }
    
    /**
     * @author: David
     * @date: Creation: 05/06/2018
     * @description: methode de test de findFromProcessus
     */
    @isTest
    static void findFromProcessus_Test(){
        String methodName='findFromProcessus';
        System.debug('### start- '+methodName);
         Test.startTest(); 
        id idProcessus=[select id from Processus__c limit 1].id;
        List<ProcessusRisque__c> processusRisque=ProcessusRisqueController.findFromProcessus(idProcessus);
        Test.stopTest();
        System.assertNotEquals(processusRisque.size(),0,'ok');        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: David
     * @date: Creation: 05/06/2018
     * @description: methode de test d'add
     */
    @isTest
    static void add_Test(){
        String methodName='add';
        System.debug('### start- '+methodName);  
        Test.startTest();
        string idRisque=[select id from risque_Entite__c limit 1].Id;
        string idProcessus=[select id from Processus__c limit 1].Id;
        ProcessusRisque__c processusRisque=new ProcessusRisque__c(processus__c=idProcessus,risqueEntite__c=idRisque);
        ProcessusRisqueController.add(processusRisque);
        Test.stopTest();
        System.assertNotEquals(processusRisque.Id,null,'ok');          
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: David
     * @date: Creation: 05/06/2018
     * @description: methode de test de remove
     */
    @isTest
    static void remove_Test(){
        String methodName='remove';
        System.debug('### start- '+methodName);
        Test.startTest();
         id idProcessus=[select id from Processus__c limit 1].id;
        Integer size=ProcessusRisqueController.findFromProcessus(idProcessus).size();
        ProcessusRisque__c processusRisque=[select Id from ProcessusRisque__c limit 1];
        ProcessusRisqueController.remove(processusRisque);
        Test.stopTest();
        System.assertEquals(ProcessusRisqueController.findFromProcessus(idProcessus).size(),(size-1),'ok');           
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @description: methode de test de getRisqueEntites
     */
    @isTest
    static void getRisqueEntites_Test(){
        String methodName='getRisqueEntites';
        System.debug('### start- '+methodName); 
         Test.startTest();
        string  EntiteId=[select Id from Account limit 1].Id;
        List<Risque_Entite__c> risqueEntite=ProcessusRisqueController.getRisqueEntites(EntiteId);
        Test.stopTest();
        System.assertNotEquals(risqueEntite,null,'ok');       
        System.debug('### end- '+methodName);
    }
    /**
     * @author: David
     * @date: 28/05/2018
     * @descrition: 
     */
    @isTest
    static void getObjectFields_TEST()
    {
        String methodName='getObjectFields';
        System.debug('### start- '+methodName);
        Test.startTest();
        System.assertNotEquals(ProcessusRisqueController.getObjectFields().size(),0,'ok');
        Test.stopTest();
        System.debug('### end- '+methodName);
    }
}