src/objects/CategorieImpact__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Impact category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Impact categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Impact__c.object
<CustomObject>
    <fields>
        <fullName>Categorie_Impact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Impact</label>
        <referenceTo>CategorieImpact__c</referenceTo>
        <relationshipLabel>Risk Impacts</relationshipLabel>
        <relationshipName>Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>risque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risk Impacts</relationshipLabel>
        <relationshipName>Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk Impact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Impacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ImpactRisqueController.cls
public with sharing class ImpactRisqueController {
     @AuraEnabled
	public static List<Impact__c> findAll(String risque){
		return [SELECT Id,Name,description__c,Categorie_Impact__r.Name,risque__c FROM Impact__c where risque__c=:risque order by Name];
	}
	
	 @AuraEnabled
	public static List<Impact__c> filterFromCategorie(String categorie, String risque){
		return [SELECT Id,Name,description__c,Categorie_Impact__r.Name,risque__c FROM Impact__c where risque__c=:risque and Categorie_Impact__c=:categorie order by Name];
	}
	
	@AuraEnabled
	public static Impact__c add(Impact__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Impact__c remove(Impact__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<CategorieImpact__c> getCategorieImpacts(){
		return [SELECT Id,Name FROM CategorieImpact__c order by Name];
	}
	@AuraEnabled
	public static Impact__c getElementById(String Id){
		return [SELECT Id,Name,description__c FROM Impact__c where Id=:Id];
	}
}