src/objects/Categorie_Risque__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk category</label>
    <nameField>
        <label>Category Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <fields>
        <fullName>categorieRisque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Category</label>
        <referenceTo>Categorie_Risque__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RisqueController.cls
public with sharing class RisqueController {
    @AuraEnabled
	public static List<Risque__c> findAll(){
		return [SELECT Id,Name,description__c,categorieRisque__r.Name,categorieRisque__r.Description__c FROM Risque__c order by Name];
	}
	
	 @AuraEnabled
	public static List<Risque__c> filterFromCategorie(String categorie){
		return [SELECT Id,Name,description__c,categorieRisque__r.Name FROM Risque__c where categorieRisque__c=:categorie order by Name];
	}
	
	@AuraEnabled
	public static Risque__c add(Risque__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Risque__c remove(Risque__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<Categorie_Risque__c> getCategorieRisques(){
		return [SELECT Id,Name FROM Categorie_Risque__c order by Name];
	}
	
	@AuraEnabled
	public static Risque__c getElementById(String Id){
		return [SELECT Id,Name,description__c,categorieRisque__c,categorieRisque__r.Description__c,categorieRisque__r.Name from Risque__c where Id=:Id];
	}
}