src/objects/CauseRisqueDetecte__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>risqueEntite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk related to the structure</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipLabel>Causes of the detected risk</relationshipLabel>
        <relationshipName>Causes_Risk_Detects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Cause of detected risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Causes of detected risk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CauseRisqueDetecteController.cls
public with sharing class CauseRisqueDetecteController {
    @AuraEnabled
	public static List<CauseRisqueDetecte__c> findAll(String risqueEntite){
		return [SELECT Id,Description__c,Name,risqueEntite__c FROM CauseRisqueDetecte__c where risqueEntite__c=:risqueEntite order by Name];
	}
	
	@AuraEnabled
	public static CauseRisqueDetecte__c add(CauseRisqueDetecte__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static CauseRisqueDetecte__c remove(CauseRisqueDetecte__c item){
		delete item;
		return item;
	} 

	@AuraEnabled
	public static CauseRisqueDetecte__c getElementById(String Id){
		return [select Id, Name,Description__c from CauseRisqueDetecte__c where Id=:Id];
	}
}