src/objects/CritereEfficacitePC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>Effectiveness criterions of CP</relationshipLabel>
        <relationshipName>Efficiency_Criterion</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Effectiveness criterion of CP</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Effectiveness criterions of CP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PartieConcernee__c.object
<CustomObject>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CritereEfficacitePCController.cls
public with sharing class CritereEfficacitePCController {
    @AuraEnabled
	public static List<CritereEfficacitePC__c> findFromPartieConcernee(String partieConcernee){
		return [SELECT Id,Name,PartieConcernee__c FROM CritereEfficacitePC__c where PartieConcernee__c=:partieConcernee order by Name];
	}

	@AuraEnabled
	public static CritereEfficacitePC__c getElementById(String Id){
		return [SELECT Id,Name,PartieConcernee__c FROM CritereEfficacitePC__c where Id=:Id];
	}
	
	@AuraEnabled
	public static CritereEfficacitePC__c add(CritereEfficacitePC__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static CritereEfficacitePC__c remove(CritereEfficacitePC__c item){
		delete item;
		return item;
	} 
}