src/objects/CritereEfficacitePC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>Effectiveness criterions of CP</relationshipLabel>
        <relationshipName>Efficiency_Criterion</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Effectiveness criterion of CP</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Effectiveness criterions of CP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ElementEntree__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Element_Entree</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Input Element</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Input Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ElementSortie__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Elements_Sortie</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Output Element</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Output Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EntiteSortie__c.object
<CustomObject>
    <fields>
        <fullName>entite__c</fullName>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Structure_Output</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>processus__c</fullName>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Structure_Output</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>output structure of output elements</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>output structures of the output elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EntiteSource__c.object
<CustomObject>
    <fields>
        <fullName>entite__c</fullName>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Source_Structures</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>processus__c</fullName>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Source_Structures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Input structure of input elements</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Input structures of input elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExigencePC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>requirements PC</relationshipLabel>
        <relationshipName>requirements_PC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>requirement  PC</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>requirements PC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ImpactPC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>Impact PC</relationshipLabel>
        <relationshipName>Impact_PC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Impact Party Concerned</label>
    <nameField>
        <label>Impact Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Impact PC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PartieConcernee__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Parties_Concerned</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Processus__c.object
<CustomObject>
    <fields>
        <fullName>dateApplication__c</fullName>
        <label>application date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pilote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pilot</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>proprietaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ownership structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>reference__c</fullName>
        <label>reference</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessusEntree__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Entry_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Input Process</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Entry Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Input Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessusRisque__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Risk_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>risqueEntite__c</fullName>
        <label>Risk Entity</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipName>Risk_Process</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process risk</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Risk Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProcessusSortie__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipLabel>Output Process</relationshipLabel>
        <relationshipName>Output_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Output Process</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Output Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Output Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <fields>
        <fullName>categorieRisque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Category</label>
        <referenceTo>Categorie_Risque__c</referenceTo>
        <relationshipLabel>Risks</relationshipLabel>
        <relationshipName>Risks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>frequence__c</fullName>
        <label>Frequency</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gravite__c</fullName>
        <label>Gravity</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>maitrise__c</fullName>
        <label>Mastery</label>
        <precision>17</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>responsable__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestProcessusLinkExtension.cls
@IsTest
public class TestProcessusLinkExtension {
    static testMethod void test(){
        //create an entity
        Account entite=new Account();
        entite.Name='Test1';
        Test.startTest();
        //insert entite
        insert entite;
        
        //test user entite
        Contact userEntite=new Contact();
        User user=[select Id,Name from User Limit 1];
        userEntite.FirstName='user.Id';
        userEntite.LastName='entite.Id';
        userEntite.AccountId=entite.Id;
        insert userEntite;
        
       //test de processus
        Processus__c processus=new Processus__c();
        processus.Name='Processus de test';
        processus.proprietaire__c=entite.Id;
        processus.pilote__c=userEntite.Id;
        processus.reference__c='REF 10.5';
        processus.version__c='5.1';
        processus.dateApplication__c=System.today();
        System.assert(ProcessusController.add(processus).Id!=null);
        System.assert(ProcessusController.findAll().size()>0);
        System.assert(ProcessusController.findFromEntite(entite.Id).size()>0);
        System.assert(ProcessusController.findUserEntites(entite.Id).size()>0);
        System.assert(ProcessusController.getElementById(processus.Id)!=null);
        System.assert(ProcessusController.getEntites().size()>0);
        //test categorie risque
        Categorie_Risque__c categorieRisque=new Categorie_Risque__c();
        categorieRisque.Name='Categorie de Test';
        CategorieRisqueController.add(categorieRisque);
        //test risque
        Risque__c risque=new Risque__c();
        risque.Name='Risque de test';
        risque.categorieRisque__c=categorieRisque.Id;
        
        RisqueController.add(risque);
        System.assert(risque.Id!=null);
        //test risque entite
        Risque_Entite__c risqueEntite=new Risque_Entite__c();
        risqueEntite.Risque__c=risque.Id;
        risqueEntite.Entite__c=entite.Id;
        risqueEntite.frequence__c=1;
        risqueEntite.gravite__c=2;
        risqueEntite.maitrise__c=2;
        risqueEntite.responsable__c=userEntite.Id;
        RisqueEntiteController.add(risqueEntite);
        //test de processus risque
        ProcessusRisque__c processusRisque=new ProcessusRisque__c();
        processusRisque.processus__c=processus.Id;
        processusRisque.risqueEntite__c=risqueEntite.Id;
        System.assert(ProcessusRisqueController.add(processusRisque).Id!=null);
        System.assert(ProcessusRisqueController.findFromProcessus(processus.Id).size()>0);
        System.assert(ProcessusRisqueController.getRisqueEntites(entite.Id).size()>0);
        //test partie concernee
        PartieConcernee__c partieConcernee=new PartieConcernee__c();
        partieConcernee.Name='Etudiant';
        partieConcernee.processus__c=processus.Id;
        System.assert(PartieConcerneeController.add(partieConcernee).Id!=null);
        System.assert(PartieConcerneeController.findFromProcessus(processus.Id).size()>0);
        System.assert(PartieConcerneeController.getElementById(partieConcernee.Id)!=null);
        //test processus en entree
        ProcessusEntree__c processusEntree=new ProcessusEntree__c();
        processusEntree.processus__c=processus.Id;
        processusEntree.source__c=processus.Id;
        System.assert(ProcessusEntreeController.add(processusEntree).Id!=null);
        System.assert(ProcessusEntreeController.findFromProcessus(processus.Id).size()>0);
        System.assert(ProcessusEntreeController.getProcessus(entite.Id).size()>0);
        //test entite source
        EntiteSource__c entiteSource=new EntiteSource__c();
        entiteSource.entite__c=entite.Id;
        entiteSource.processus__c=processus.Id;
        System.assert(EntiteSourceController.add(entiteSource).Id!=null);
        System.assert(EntiteSourceController.findFromProcessus(processus.Id).size()>0);
        System.assert(EntiteSourceController.getEntites().size()>0);
        //test entite source
        EntiteSortie__c entiteSortie=new EntiteSortie__c();
        entiteSortie.entite__c=entite.Id;
        entiteSortie.processus__c=processus.Id;
        System.assert(EntiteSortieController.add(entiteSortie).Id!=null);
        System.assert(EntiteSortieController.findFromProcessus(processus.Id).size()>0);
        System.assert(EntiteSortieController.getEntites().size()>0);
        //test element entree
        ElementEntree__c elementEntree=new ElementEntree__c();
        elementEntree.processus__c=processus.Id;
        elementEntree.Name='Elment 1 en entree';
        System.assert(ElementEntreeController.add(elementEntree).Id!=null);
        System.assert(ElementEntreeController.findFromProcessus(processus.Id).size()>0);
        //test element Sortie
        ElementSortie__c elementSortie=new ElementSortie__c();
        elementSortie.processus__c=processus.Id;
        elementSortie.Name='Elment 1 en sortie';
        System.assert(ElementSortieController.add(elementSortie).Id!=null);
        System.assert(ElementSortieController.findFromProcessus(processus.Id).size()>0);
        //test processus en sortie
        ProcessusSortie__c processusSortie=new ProcessusSortie__c();
        processusSortie.processus__c=processus.Id;
        processusSortie.destination__c=processus.Id;
        System.assert(ProcessusSortieController.add(processusSortie).Id!=null);
        System.assert(ProcessusSortieController.findFromProcessus(processus.Id).size()>0);
        System.assert(ProcessusSortieController.getProcessus(entite.Id).size()>0);


        //Dans partie Concernee
        //test partie interessee
        PartieInteressee__c partieInteressee=new PartieInteressee__c();
        partieInteressee.Name='Etudiant';
        partieInteressee.PartieConcernee__c=partieConcernee.Id;
        System.assert(PartieInteresseeController.add(partieInteressee)!=null);
        System.assert(PartieInteresseeController.findFromPartieConcernee(partieConcernee.Id).size()>0);
        //impact partie concernee
        ImpactPC__c impactPC=new ImpactPC__c();
        impactPC.Name='Impact PC 1';
        impactPC.PartieConcernee__c=partieConcernee.Id;
        System.assert(ImpactPCController.add(impactPC)!=null);
        System.assert(ImpactPCController.findFromPartieConcernee(partieConcernee.Id).size()>0);
        //mode surveillance partie concernee
        ModeSurveillancePC__c modeSurveillancePC=new ModeSurveillancePC__c();
        modeSurveillancePC.PartieConcernee__c=partieConcernee.Id;
        modeSurveillancePC.Name='Mode de surveillance 1 PC';
        System.assert(ModeSurveillancePCController.add(modeSurveillancePC)!=null);
        System.assert(ModeSurveillancePCController.findFromPartieConcernee(partieConcernee.Id).size()>0);
        //test des Revues Partie Concernee
        RevuePC__c revuePC=new RevuePC__c();
        revuePC.Name='Revue Partie Concernee';
        revuePC.PartieConcernee__c=partieConcernee.Id;
        RevuePCController.add(revuePC);
        System.assert(revuePC.Id!=null);
        System.assert(RevuePCController.findFromPartieConcernee(partieConcernee.Id).size()>0);
        //test exigence Partie concernee
        ExigencePC__c exigencePC=new ExigencePC__c();
        exigencePC.Name='Exigence 1 partie concernee';
        exigencePC.PartieConcernee__c=partieConcernee.Id;
        System.assert(ExigencePCController.add(exigencePC)!=null);
        System.assert(ExigencePCController.findFromPartieConcernee(partieConcernee.Id).size()>0);
        //test critere efficacite
        CritereEfficacitePC__c critereEfficacitePC=new CritereEfficacitePC__c();
        critereEfficacitePC.Name='Critere efficacité PC';
        critereEfficacitePC.PartieConcernee__c=partieConcernee.Id;
        System.assert(CritereEfficacitePCController.add(critereEfficacitePC)!=null);
        System.assert(CritereEfficacitePCController.findFromPartieConcernee(partieConcernee.Id).size()>0);
        
        
        
        
        
        
        
        
        
        
        //remove Critere Efficacité Partie Concernee
        System.assert(CritereEfficacitePCController.remove(critereEfficacitePC)!=null);
        //remove Exigence Partie Concernee
        System.assert(ExigencePCController.remove(exigencePC)!=null);
        //remove Revues Partie COncernee
        System.assert(RevuePCController.remove(revuePC)!=null);
        //remove Mode de surveillance partie concernee
        System.assert(ModeSurveillancePCController.remove(modeSurveillancePC)!=null);
        //remove impact partie concernee
        System.assert(ImpactPCController.remove(impactPC)!=null);
        //remove partie interessee
        System.assert(PartieInteresseeController.remove(partieInteressee)!=null);
        //remove element Sortie
        System.assert(ElementSortieController.remove(elementSortie)!=null);
        //remove element entree
        System.assert(ElementEntreeController.remove(elementEntree)!=null);
        //delete entite sortie
       	System.assert(EntiteSortieController.remove(entiteSortie)!=null);
        //delete entite source
        System.assert(EntiteSourceController.remove(entiteSource)!=null);
        //delete processus sortie
        System.assert(ProcessusSortieController.remove(processusSortie)!=null);
        //delete processus entree
        System.assert(ProcessusEntreeController.remove(processusEntree)!=null);
        //delete partie concernee
        System.assert(PartieConcerneeController.remove(partieConcernee)!=null);
        //delete processus risque
         System.assert(ProcessusRisqueController.remove(processusRisque)!=null);
        //delete processus
        System.assert(ProcessusController.remove(processus)!=null);
        //delete risque entite
        System.assert(RisqueEntiteController.remove(risqueEntite)!=null);
        
        Test.stopTest();
    }
}