src/objects/ElementEntree__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Element_Entree</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Input Element</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Input Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Processus__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ElementEntreeController.cls
public with sharing class ElementEntreeController {
    @AuraEnabled
	public static List<ElementEntree__c> findFromProcessus(String processus){
		return [SELECT Id,Name,processus__c FROM ElementEntree__c where processus__c=:processus order by Name];
	}
	
	@AuraEnabled
	public static ElementEntree__c add(ElementEntree__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ElementEntree__c remove(ElementEntree__c item){
		delete item;
		return item;
	}  
	@AuraEnabled
	public static ElementEntree__c getElementById(String Id){
		return [SELECT Id,Name,processus__c FROM ElementEntree__c where Id=:Id];
	}
}