src/objects/ElementSortie__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Elements_Sortie</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Output Element</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Output Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Processus__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ElementSortieController.cls
public with sharing class ElementSortieController {
     @AuraEnabled
	public static List<ElementSortie__c> findFromProcessus(String processus){
		return [SELECT Id,Name,processus__c FROM ElementSortie__c where processus__c=:processus order by Name];
	}
	
	@AuraEnabled
	public static ElementSortie__c getElementById(String Id){
		return [SELECT Id,Name,processus__c FROM ElementSortie__c where Id=:Id];
	}
	
	@AuraEnabled
	public static ElementSortie__c add(ElementSortie__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ElementSortie__c remove(ElementSortie__c item){
		delete item;
		return item;
	}  
}