src/objects/EntiteSortie__c.object
<CustomObject>
    <fields>
        <fullName>entite__c</fullName>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Structure_Output</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>processus__c</fullName>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Structure_Output</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>output structure of output elements</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>output structures of the output elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Processus__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EntiteSortieController.cls
public with sharing class EntiteSortieController {
     @AuraEnabled
	public static List<EntiteSortie__c> findFromProcessus(String processus){
		return [SELECT Id,entite__r.Name,entite__r.Phone,entite__r.Website,entite__r.Type FROM EntiteSortie__c where processus__c=:processus order by entite__r.Name];
	
	}
	
	@AuraEnabled
	public static EntiteSortie__c add(EntiteSortie__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static EntiteSortie__c remove(EntiteSortie__c item){
		delete item;
		return item;
	} 
	
	  @AuraEnabled
	public static List<Account> getEntites(){
		return [SELECT Id,Name FROM Account where  RecordTypeId=:EntiteController.getStructureRecordTypeId() order by Name ];
	}
}