src/objects/Entite_Affectee__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affected Organizations</relationshipLabel>
        <relationshipName>Entites_Affectee</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>risque_Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Detected Risk</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipLabel>Affected Organizations</relationshipLabel>
        <relationshipName>Entites_Affectee</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Affected Organization</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affected Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EntiteAffecteeController.cls
public with sharing class EntiteAffecteeController {
	
	 public static Id getStructureRecordTypeId(){
         Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                  .get('Structure').getRecordTypeId();
        return RecordTypeId;
    }
    
     @AuraEnabled
	public static List<Entite_Affectee__c> findAll(String risqueEntite){
 		return [SELECT Id,Entite__r.Name,Entite__r.Phone,risque_Entite__r.Risque__r.Name FROM Entite_Affectee__c where risque_Entite__c=:risqueEntite];
  }
    
  
	
	@AuraEnabled
	public static Entite_Affectee__c add(Entite_Affectee__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Entite_Affectee__c remove(Entite_Affectee__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<Account> getEntites(){
		return [SELECT Id,Name FROM Account where RecordTypeId=:EntiteController.getStructureRecordTypeId()order by Name];
	}
}