src/objects/ExigencePC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>requirements PC</relationshipLabel>
        <relationshipName>requirements_PC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>requirement  PC</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>requirements PC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PartieConcernee__c.object
<CustomObject>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExigencePCController.cls
public with sharing class ExigencePCController {
    @AuraEnabled
	public static List<ExigencePC__c> findFromPartieConcernee(String partieConcernee){
		return [SELECT Id,Name,PartieConcernee__c FROM ExigencePC__c where PartieConcernee__c=:partieConcernee order by Name];
	}
	
	@AuraEnabled
	public static ExigencePC__c add(ExigencePC__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ExigencePC__c remove(ExigencePC__c item){
		delete item;
		return item;
	} 
	  @AuraEnabled
	public static ExigencePC__c getElementById(String Id){
		return [SELECT Id,Name,PartieConcernee__c FROM ExigencePC__c where Id=:Id];
	}
}