src/objects/Impact__c.object
<CustomObject>
    <fields>
        <fullName>Categorie_Impact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Impact</label>
        <referenceTo>CategorieImpact__c</referenceTo>
        <relationshipLabel>Risk Impacts</relationshipLabel>
        <relationshipName>Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>risque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risk Impacts</relationshipLabel>
        <relationshipName>Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk Impact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Impacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Impact_Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>ImpactRisque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Impact</label>
        <referenceTo>Impact__c</referenceTo>
        <relationshipName>Entity_Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>risque_Entite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk entity</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipName>Entity_Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk Impact</label>
    <nameField>
        <displayFormat>Impact-{0000}</displayFormat>
        <label>Impact  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detected Risk Impacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mesure_Prevention__c.object
<CustomObject>
    <fields>
        <fullName>CategorieMesurePrevention__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Measurement Prevension</label>
        <referenceTo>Categorie_Mesure_Prevention__c</referenceTo>
        <relationshipName>Measures_Prevention</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipName>Measures_Prevention</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>preventative measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>preventative measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mesure_Prevention_Risque_Detecte__c.object
<CustomObject>
    <fields>
        <fullName>mesure_Prevention__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Measure Prevention</label>
        <referenceTo>Mesure_Prevention__c</referenceTo>
        <relationshipName>Measures_Preventions_Risk_Detects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>risque_Detecte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>detects  risk</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipName>Measures_Preventions_Risk_Detects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Detected risk prevention measure</label>
    <nameField>
        <displayFormat>Mesure-{0000}</displayFormat>
        <label>Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detected risk prevention measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RisqueEntiteManagement.cls
/*
 * 
 * 
 */
public class RisqueEntiteManagement {
    private static RisqueEntiteManagement instance;
    
    private RisqueEntiteManagement(){
        
    }
    
    public static RisqueEntiteManagement getInstance(){
        if(instance==null){
            instance=new RisqueEntiteManagement();
        }
        return instance;
    }
    //return mesure prevention risque detecte according ti the risque entite
    public List<Mesure_Prevention_Risque_Detecte__c> getMesurePreventionRisqueEntite(Map<Id,Risque_Entite__c> risqueEntites){
        List<Mesure_Prevention__c> mesurePreventions=[select CategorieMesurePrevention__c,Name, Description__c,Risque__c from Mesure_Prevention__c where Risque__c in :risqueEntites.keySet()];
        List<Mesure_Prevention_Risque_Detecte__c> mesureRDs=new List<Mesure_Prevention_Risque_Detecte__c>();
        for(Mesure_Prevention__c mesurePrev:mesurePreventions){
            mesureRDs.add(new Mesure_Prevention_Risque_Detecte__c(mesure_Prevention__c=mesurePrev.Id));
            //risque_Detecte__c=risqueEntites.get(mesurePrev.Risque__c).Id
        }
        
        return mesureRds;
    }
    
    //return impact risque detecte according to the risque entite
    public List<Impact_Risque_Entite__c> getImpactRisqueEntite(Map<Id,Risque_Entite__c> risqueEntites){
        List<Impact__c> impacts=[select Categorie_Impact__c,Name, Description__c,Risque__c from Impact__c where Risque__c in :risqueEntites.keySet()];
        List<Impact_Risque_Entite__c> impactRDs=new List<Impact_Risque_Entite__c>();
        for(Impact__c impact:impacts){
            impactRDs.add(new Impact_Risque_Entite__c(impactRisque__c=impact.Id,risque_Entite__c=risqueEntites.get(impact.Risque__c).Id));
        }
        
        return  impactRds;
    }
}