src/objects/Impact__c.object
<CustomObject>
    <fields>
        <fullName>risque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risk Impacts</relationshipLabel>
        <relationshipName>Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk Impact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Impacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Impact_Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>ImpactRisque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk Impact</label>
        <referenceTo>Impact__c</referenceTo>
        <relationshipName>Entity_Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>risque_Entite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk entity</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipName>Entity_Risk_Impacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk Impact</label>
    <nameField>
        <displayFormat>Impact-{0000}</displayFormat>
        <label>Impact  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detected Risk Impacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ImpactRisqueEntiteController.cls
public with sharing class ImpactRisqueEntiteController {
     @AuraEnabled
	public static List<Impact_Risque_Entite__c> findAll(String risqueEntite){
		return [SELECT Id,ImpactRisque__r.Name,risque_Entite__r.Risque__r.Name FROM Impact_Risque_Entite__c where risque_Entite__c=:risqueEntite];
	}
	
	@AuraEnabled
	public static Impact_Risque_Entite__c add(Impact_Risque_Entite__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Impact_Risque_Entite__c remove(Impact_Risque_Entite__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<Impact__c> getImpacts(String risque){
		return [SELECT Id,Name FROM Impact__c where risque__c=:risque order by Name];
	}
}