src/objects/ImpactPC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>Impact PC</relationshipLabel>
        <relationshipName>Impact_PC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Impact Party Concerned</label>
    <nameField>
        <label>Impact Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Impact PC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PartieConcernee__c.object
<CustomObject>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ImpactPCController.cls
public with sharing class ImpactPCController {
     @AuraEnabled
	public static List<ImpactPC__c> findFromPartieConcernee(String partieConcernee){
		return [SELECT Id,Name,PartieConcernee__c FROM ImpactPC__c where PartieConcernee__c=:partieConcernee order by Name];
	}
	
	@AuraEnabled
	public static ImpactPC__c add(ImpactPC__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ImpactPC__c remove(ImpactPC__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static ImpactPC__c getElementById(String Id){
		return [SELECT Id,Name,PartieConcernee__c FROM ImpactPC__c where Id=:Id];
	}
}