src/objects/Mesure_Prevention__c.object
<CustomObject>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipName>Measures_Prevention</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>preventative measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>preventative measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mesure_Prevention_Risque_Detecte__c.object
<CustomObject>
    <fields>
        <fullName>mesure_Prevention__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Measure Prevention</label>
        <referenceTo>Mesure_Prevention__c</referenceTo>
        <relationshipName>Measures_Preventions_Risk_Detects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Detected risk prevention measure</label>
    <nameField>
        <displayFormat>Mesure-{0000}</displayFormat>
        <label>Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detected risk prevention measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MesurePreventionRisqueDetecteController.cls
public with sharing class MesurePreventionRisqueDetecteController {
   
      @AuraEnabled
	public static List<Mesure_Prevention_Risque_Detecte__c> findAll(String ParamRisqueEntite){
		return [SELECT Id,mesure_Prevention__r.Name,risk_tracking_parameter__r.Risque__r.Name FROM Mesure_Prevention_Risque_Detecte__c where risk_tracking_parameter__c=:ParamRisqueEntite];
	}
	
	@AuraEnabled
	public static Mesure_Prevention_Risque_Detecte__c add(Mesure_Prevention_Risque_Detecte__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Mesure_Prevention_Risque_Detecte__c remove(Mesure_Prevention_Risque_Detecte__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<Mesure_Prevention__c> getMesurePreventions(String risque){
		return [SELECT Id,Name FROM Mesure_Prevention__c where Risque__c=:risque order by Name];	
	}
}