src/objects/ModeSurveillancePC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>Surveillance Modes</relationshipLabel>
        <relationshipName>Surveillance_Modes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PC Surveillance Mode</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveillance Modes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PartieConcernee__c.object
<CustomObject>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ModeSurveillancePCController.cls
public with sharing class ModeSurveillancePCController {
     @AuraEnabled
	public static List<ModeSurveillancePC__c> findFromPartieConcernee(String partieConcernee){
		return [SELECT Id,Name,PartieConcernee__c FROM ModeSurveillancePC__c where PartieConcernee__c=:partieConcernee order by Name];
	}
	
	@AuraEnabled
	public static ModeSurveillancePC__c add(ModeSurveillancePC__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ModeSurveillancePC__c remove(ModeSurveillancePC__c item){
		delete item;
		return item;
	}
	
	@AuraEnabled
	public static ModeSurveillancePC__c getElementById(String Id){
		return [SELECT Id,Name, PartieConcernee__c  from ModeSurveillancePC__c where Id=:Id];
	}
	
}