src/objects/ParamRisqueEntite__c.object
<CustomObject>
    <fields>
        <fullName>entite__c</fullName>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Entite_Risk_Parameters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>risque__c</fullName>
        <label>risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipName>Entite_Risk_Parameters</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk Tracking Parameter</label>
    <nameField>
        <label>Entite Risk Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Tracking Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Action__c.object
<CustomObject>
    <fields>
        <fullName>commentaire__c</fullName>
        <label>comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>date_commencement__c</fullName>
        <label>date of detection</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>echeancier__c</fullName>
        <label>timeline</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>etat__c</fullName>
        <defaultValue>true</defaultValue>
        <label>state</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gestionnaire__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>administrator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>PA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlanActionPreventifController.cls
public with sharing class PlanActionPreventifController {
    public static Id getPlanActionPreventifRecordTypeId(){
         Id recordTypeId = Schema.SObjectType.Plan_Action__c.getRecordTypeInfosByName()
                  .get('Plan Action Preventif').getRecordTypeId();
        return recordTypeId;
    }
    
    @AuraEnabled
	public static List<Plan_Action__c> findAllByParamRisqueEntite(String paramRisqueEntite){
		return [SELECT Id,commentaire__c,date_commencement__c,echeancier__c,etat__c,gestionnaire__r.Name,Name,gestionnaire__c,ParamRisqueEntite__c,ParamRisqueEntite__r.entite__c FROM Plan_Action__c where ParamRisqueEntite__c=:paramRisqueEntite and RecordTypeId=:PlanActionPreventifController.getPlanActionPreventifRecordTypeId() order by Name];
	}
	
	@AuraEnabled
	public static List<Plan_Action__c> findAll(){
		return [SELECT Id,commentaire__c,date_commencement__c,echeancier__c,etat__c,gestionnaire__r.Name,Name,gestionnaire__c,ParamRisqueEntite__c,ParamRisqueEntite__r.entite__c FROM Plan_Action__c where RecordTypeId=:PlanActionPreventifController.getPlanActionPreventifRecordTypeId() order by Name];
	}
	
	@AuraEnabled
	public static Plan_Action__c add(Plan_Action__c item){
		item.RecordTypeId=PlanActionPreventifController.getPlanActionPreventifRecordTypeId();
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static Plan_Action__c remove(Plan_Action__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static List<Contact> findUserEntites(String entite){
		return [select Id,Name,AccountId from Contact where AccountId=:entite];
	}
	
	
	@AuraEnabled
	public static Plan_Action__c getElementById(String Id){
		return [SELECT Id,commentaire__c,date_commencement__c,echeancier__c,etat__c,
		gestionnaire__r.Name,Name,gestionnaire__c,ParamRisqueEntite__c,
		ParamRisqueEntite__r.risque__r.Name,ParamRisqueEntite__r.entite__c FROM Plan_Action__c where Id=:Id];
	}
}