src/objects/PartieConcernee__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Parties_Concerned</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Processus__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartieConcerneeController.cls
public with sharing class PartieConcerneeController {
     @AuraEnabled
	public static List<PartieConcernee__c> findFromProcessus(String processus){
		return [SELECT Id,Name,processus__c FROM PartieConcernee__c where processus__c=:processus order by Name];
	}
	
	@AuraEnabled
	public static PartieConcernee__c add(PartieConcernee__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static PartieConcernee__c remove(PartieConcernee__c item){
		delete item;
		return item;
	}  
	
	@AuraEnabled
	public static PartieConcernee__c getElementById(String Id){
		return [SELECT Id,Name,processus__c FROM PartieConcernee__c where Id=:Id];
	}
}