src/objects/PartieConcernee__c.object
<CustomObject>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PartieInteressee__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Party Concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>Interested Parties</relationshipLabel>
        <relationshipName>Interested_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interested party</label>
    <nameField>
        <label>Interested party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interested Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartieInteresseeController.cls
public with sharing class PartieInteresseeController {
     @AuraEnabled
	public static List<PartieInteressee__c> findFromPartieConcernee(String partieConcernee){
		return [SELECT Id,Name,PartieConcernee__c FROM PartieInteressee__c where PartieConcernee__c=:partieConcernee order by Name];
	}
	
	@AuraEnabled
	public static PartieInteressee__c add(PartieInteressee__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static PartieInteressee__c getElementById(String Id){
		return [SELECT Id,Name,PartieConcernee__c FROM PartieInteressee__c where Id=:Id];
	}
	
	@AuraEnabled
	public static PartieInteressee__c remove(PartieInteressee__c item){
		delete item;
		return item;
	} 
}