src/objects/PartieConcernee__c.object
<CustomObject>
    <label>Concerned Party</label>
    <nameField>
        <label>Party Concerned Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concerned Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RevuePC__c.object
<CustomObject>
    <fields>
        <fullName>PartieConcernee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Party concerned</label>
        <referenceTo>PartieConcernee__c</referenceTo>
        <relationshipLabel>Revues_PC</relationshipLabel>
        <relationshipName>Revues_PC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reviewed parties concerned</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revues PC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RevuePCController.cls
public with sharing class RevuePCController {
     @AuraEnabled
	public static List<RevuePC__c> findFromPartieConcernee(String partieConcernee){
		return [SELECT Id,Name,PartieConcernee__c FROM RevuePC__c where PartieConcernee__c=:partieConcernee order by Name];
	}
	
	@AuraEnabled
	public static RevuePC__c add(RevuePC__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static RevuePC__c remove(RevuePC__c item){
		delete item;
		return item;
	} 
	@AuraEnabled
	public static RevuePC__c getElementById(String Id){
		return [SELECT Id,Name,PartieConcernee__c
		 FROM RevuePC__c where Id=:Id];
	}
}