src/objects/Processus__c.object
<CustomObject>
    <fields>
        <fullName>dateApplication__c</fullName>
        <label>application date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pilote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pilot</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>proprietaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ownership structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>reference__c</fullName>
        <label>reference</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestChartProcessus.cls
@IsTest
public class TestChartProcessus {
    static testMethod void test(){
        //create an entity
        Account entite=new Account();
        entite.Name='Test1';
        insert entite;
        //test user entite
        Contact userEntite=new Contact();
        userEntite.FirstName='user.Id';
        userEntite.AccountId=entite.Id;
        userEntite.LastName='true';
        insert userEntite;
        //test de processus
        Processus__c processus=new Processus__c();
        processus.Name='Processus de test';
        processus.proprietaire__c=entite.Id;
        processus.pilote__c=userEntite.Id;
        processus.reference__c='REF 10.5';
        processus.version__c='5.1';
        processus.dateApplication__c=System.today();
        System.assert(ProcessusController.add(processus).Id!=null);
        
        Test.startTest();
        String annee='2017';
        System.assert(ChartProcessusController.processusByEntite(annee).size()>0);
        Test.stopTest();
    }
}