src/objects/Processus__c.object
<CustomObject>
    <fields>
        <fullName>copilote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>copilot</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Process (copilot)</relationshipLabel>
        <relationshipName>Process1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dateApplication__c</fullName>
        <label>application date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>finalite__c</fullName>
        <label>finality</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pilote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pilot</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>proprietaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ownership structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>reference__c</fullName>
        <label>reference</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessusController.cls
public with sharing class ProcessusController {
	
	@AuraEnabled
	public static List<Processus__c> findAll(){
		return [SELECT Id,copilote__c,dateApplication__c,finalite__c,Name,pilote__c,proprietaire__c,reference__c,version__c FROM Processus__c order by Name];
	}
	
    @AuraEnabled
	public static List<Processus__c> findFromEntite(String entite){
		return [SELECT Id,copilote__c,dateApplication__c,finalite__c,Name,pilote__c,proprietaire__c,reference__c,version__c FROM Processus__c where proprietaire__c=:entite order by Name];
	}
    
	@AuraEnabled
	public static Processus__c add(Processus__c item){
		upsert item;
		return item;
	}
	
	
	@AuraEnabled
	public static Processus__c remove(Processus__c item){
		delete item;
		return item;
	} 
	
	@AuraEnabled
	public static Processus__c getElementById(String Id){
		return [SELECT Id,copilote__r.Name,dateApplication__c,finalite__c,Name,pilote__r.Name,proprietaire__c,reference__c,version__c from Processus__c where Id=:Id];
	}
	
	@AuraEnabled
	public static List<Account> getEntites(){
		return [Select Id,Name from Account where RecordTypeId=:EntiteController.getStructureRecordTypeId()];
	}
    
    @AuraEnabled
	public static List<Contact> findUserEntites(String entite){
		return [select Id,Name from Contact where AccountId=:entite];
	}
	
	@AuraEnabled
	public static List<Processus__c> findAllByRiskManager(String idRiskManager){
		return [SELECT Id,Name,pilote__c,dateApplication__c FROM Processus__c WHERE  pilote__c =: idRiskManager and pilote__r.RecordTypeId=:RiskManagerController.getRiskManagerRecordTypeId()  order by dateApplication__c desc];
	}
	
	
}