src/objects/Processus__c.object
<CustomObject>
    <fields>
        <fullName>dateApplication__c</fullName>
        <label>application date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>proprietaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ownership structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessusSortie__c.object
<CustomObject>
    <fields>
        <fullName>destination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>destination</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipLabel>Output Process (destination)</relationshipLabel>
        <relationshipName>Output_Process1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipLabel>Output Process</relationshipLabel>
        <relationshipName>Output_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Output Process</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Output Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Output Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessusSortieController.cls
public with sharing class ProcessusSortieController {
     @AuraEnabled
	public static List<ProcessusSortie__c> findFromProcessus(String processus){
		return [SELECT Id,destination__r.Name,destination__r.dateApplication__c,destination__r.version__c,destination__r.proprietaire__r.Name FROM ProcessusSortie__c where processus__c=:processus order by destination__r.Name];
	}
	
	@AuraEnabled
	public static ProcessusSortie__c add(ProcessusSortie__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ProcessusSortie__c remove(ProcessusSortie__c item){
		delete item;
		return item;
	} 
	
	  @AuraEnabled
	public static List<Processus__c> getProcessus(String entite){
		return [SELECT Id,Name FROM Processus__c where proprietaire__c=:entite order by Name ];
	}
}