src/objects/Processus__c.object
<CustomObject>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessusRisque__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Risk_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>risqueEntite__c</fullName>
        <label>Risk Entity</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipName>Risk_Process</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process risk</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Risk Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Date_Detection__c</fullName>
        <label>Date of detection</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>criticite__c</fullName>
        <formula>( frequence__c  +  gravite__c ) *  maitrise__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Criticality</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>etat__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessusRisqueController.cls
public with sharing class ProcessusRisqueController {
    
    @AuraEnabled
	public static List<ProcessusRisque__c> findFromProcessus(String processus){
		return [SELECT Id,risqueEntite__r.Risque__r.Name,risqueEntite__r.Date_Detection__c,risqueEntite__r.etat__c,risqueEntite__r.criticite__c FROM ProcessusRisque__c where processus__c=:processus order by risqueEntite__r.Risque__r.Name];
	}
	
	@AuraEnabled
	public static ProcessusRisque__c add(ProcessusRisque__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ProcessusRisque__c remove(ProcessusRisque__c item){
		delete item;
		return item;
	} 
	
	  @AuraEnabled
	public static List<Risque_Entite__c> getRisqueEntites(String entite){
		return [SELECT Id,Risque__r.Name FROM Risque_Entite__c where Entite__c=:entite order by Risque__r.Name ];
	}
}