src/objects/Processus__c.object
<CustomObject>
    <fields>
        <fullName>dateApplication__c</fullName>
        <label>application date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>proprietaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ownership structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>version__c</fullName>
        <label>version</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessusEntree__c.object
<CustomObject>
    <fields>
        <fullName>processus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Entry_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>source</label>
        <referenceTo>Processus__c</referenceTo>
        <relationshipName>Entry_Process1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Input Process</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Entry Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Input Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessusEntreeController.cls
public with sharing class ProcessusEntreeController {
   
   @AuraEnabled
	public static List<ProcessusEntree__c> findFromProcessus(String processus){
		return [SELECT Id,source__r.Name,source__r.dateApplication__c,source__r.version__c,source__r.proprietaire__r.Name FROM ProcessusEntree__c where processus__c=:processus order by source__r.Name];
	}
	
	@AuraEnabled
	public static ProcessusEntree__c add(ProcessusEntree__c item){
		upsert item;
		return item;
	}
	
	@AuraEnabled
	public static ProcessusEntree__c remove(ProcessusEntree__c item){
		delete item;
		return item;
	} 
	
	  @AuraEnabled
	public static List<Processus__c> getProcessus(String entite){
		return [SELECT Id,Name FROM Processus__c where proprietaire__c=:entite order by Name ];
	}
  
}