src/objects/Processus__c.object
<CustomObject>
    <fields>
        <fullName>dateApplication__c</fullName>
        <label>application date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>proprietaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ownership structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChartProcessusController.cls
public with sharing class ChartProcessusController {
    @AuraEnabled
	public static  Map<String, Object> processusByEntite(String annee){
		List<Account> entites= [SELECT Id,Name FROM Account where RecordTypeId=:EntiteController.getStructureRecordTypeId() order by Id];
		List<String> labels=new List<String>{};
		List<Integer> datas=new List<Integer>{};
		for(Account entite:entites){
			labels.add(entite.Name);
			AggregateResult result=[SELECT count(Id) FROM Processus__c where proprietaire__c=:entite.Id  and CALENDAR_YEAR(dateApplication__c)=:Integer.valueOf(annee)];
			datas.add(Integer.valueOf(result.get('expr0')));
		}
		
		return new Map<String, Object>{'labels' => labels, 'data' => datas};
	
	}
}