src/objects/Projet__c.object
<CustomObject>
    <fields>
        <fullName>Etat__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque__c.object
<CustomObject>
    <label>Risk</label>
    <nameField>
        <label>Risque Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Date_Detection__c</fullName>
        <label>Date of detection</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risque__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Risk</label>
        <referenceTo>Risque__c</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>criticite__c</fullName>
        <formula>( frequence__c  +  gravite__c ) *  maitrise__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Criticality</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>etat__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_projet__c.object
<CustomObject>
    <fields>
        <fullName>Projet__c</fullName>
        <label>Project</label>
        <referenceTo>Projet__c</referenceTo>
        <relationshipLabel>Risques projets</relationshipLabel>
        <relationshipName>Risques_projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risque_detecte__c</fullName>
        <label>Detected risk</label>
        <referenceTo>Risque_Entite__c</referenceTo>
        <relationshipLabel>Risques projets</relationshipLabel>
        <relationshipName>Risques_projets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Risk project</label>
    <nameField>
        <displayFormat>RisqueProjet-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risques projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RisqueProjetController.cls
public with sharing class  RisqueProjetController {
	
	@AuraEnabled
	public static List<Risque_projet__c> findAll(String projet){
     return [SELECT Id,Risque_detecte__r.Risque__r.Name,Risque_detecte__r.Date_Detection__c,Risque_detecte__r.etat__c,Risque_detecte__r.criticite__c FROM Risque_projet__c where Projet__c=:projet];
		
	}
	
	    @AuraEnabled 
	public static List<Risque_Entite__c> getRisqueEntites(String entite){
		return [SELECT Id,Risque__r.Name FROM Risque_Entite__c where Entite__c=:entite order by Risque__r.Name ];
	}
	
	    
    @AuraEnabled
    public static Risque_projet__c add(Risque_projet__c item){
    	upsert item;
    	return item;
    	
    }
    
    @AuraEnabled 
    public static Risque_projet__c remove(Risque_projet__c item){
    	delete item;
    	return item;
    }
    
    
}