src/objects/Projet__c.object
<CustomObject>
    <fields>
        <fullName>Cout__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_debut__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_prevue__c</fullName>
        <label>Assigned end date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Etat__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Responsable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projet</relationshipLabel>
        <relationshipName>Projet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Web_du_projet__c</fullName>
        <label>Project website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projet</relationshipLabel>
        <relationshipName>Projet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <recordTypes>
        <fullName>structure</fullName>
        <active>true</active>
        <description>Project object used as structure in Risk Manager App</description>
        <label>structure</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Risque_Entite__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Structure</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>etat__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>responsable__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Risques_Entites</relationshipLabel>
        <relationshipName>Risques_Entites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Detected Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risques detectés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjetController.cls
public with sharing class ProjetController {
	   public static Id getStructureRecordTypeId(){
         Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                  .get('Structure').getRecordTypeId();
        return RecordTypeId;
    }
    
    @AuraEnabled
    public static Projet__c getElementById(String Id){
    	return [SELECT Id,Cout__c, Date_debut__c, Date_fin_prevue__c,Description__c,Etat__c,Name,Responsable__c,Responsable__r.Name,Site_Web_du_projet__c,Structure__c,Structure__r.Name,Structure__r.Description FROM Projet__c where Id=:Id];
    	
    }
    
    @AuraEnabled
    public static list<Projet__c> findAll(){
   return [SELECT Id,Cout__c, Date_debut__c,Date_fin_prevue__c,Description__c,Etat__c,Name,Responsable__r.Name,Site_Web_du_projet__c,Structure__r.Name FROM Projet__c order by Date_debut__c desc ];
    	
    }
    
    @AuraEnabled
    public static list<Projet__c> findAllByStructure(String Structure){
    
    	    	return [SELECT Id,Cout__c, Date_debut__c,Date_fin_prevue__c,Description__c,Etat__c,Name,Responsable__r.Id,Responsable__r.Name,Site_Web_du_projet__c,Structure__r.Name,Structure__r.Description FROM Projet__c where Structure__c=:Structure order by Date_debut__c desc];
    	
    }
        @AuraEnabled
    public static list<Projet__c> findAllByRiskManager(String riskmanager){
    
     return [SELECT Id,Cout__c, Date_debut__c,Date_fin_prevue__c,Description__c,Etat__c,Name,Responsable__r.Name,Responsable__r.Id,Site_Web_du_projet__c,Structure__r.Name,Structure__r.Description FROM Projet__c where Responsable__c=:riskmanager and Responsable__r.RecordTypeId=:RiskManagerController.getRiskManagerRecordTypeId()  order by Date_debut__c desc];
    	
    }
     
    @AuraEnabled
    public static Projet__c add(Projet__c item){
    	if(item!=null){
    	upsert item;
    	return item;
    	}
    	return item;
    	
    }
    
    @AuraEnabled 
    public static Projet__c remove(Projet__c item){
    	delete item;
    	return item;
    }
    
    @AuraEnabled 
    public static List<Account> getEntites(){
    	
    	return[SELECT Id,Name FROM Account  where  RecordTypeId=:EntiteController.getStructureRecordTypeId()order by Name ];
    	
    }
    
    @AuraEnabled 
    public static List<Risque_Entite__c> findRisqueDetectes(String entite){
    	return [SELECT Id,Name FROM Risque_Entite__c where Entite__c=:entite];
    	
    }
    
    	@AuraEnabled
	public static List<Contact> findUserEntites(String entite){
		return [select Id,Name from Contact where AccountId=:entite];
	}

    
    
    
}